import Head from 'next/head'
import Link from 'next/link'
import Sin from './components/sin'

export default function Home() {
  return (
    <>
      <Head>
        <title>Moiré</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black h-screen w-screentext-center lg:text-start overflow-x-hidden flex flex-col justify-between">
        <div className='pt-24 px-24 w-4/5 space-y-4 bg-transparent'>
          <div className='font-heading font-bold'>
          <h1 className='text-4xl text-neutral-300'>Moiré</h1>
          <p className='text-xl  text-neutral-500'>Intriguing math simulations</p>
          </div>
          <ul className='text-neutral-300 text-lg underline underline-offset-1 hover:underline-offset-2'>
            <li>
              <Link href="/sim/parabola">
                Exploring the parabola
              </Link>
            </li>
          </ul>
        </div>
        <div className='opacity-60'>
          <Sin/>
        </div>
        </main>    
    </>
  )
}
